# Generated by Django 3.0.7 on 2020-06-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0002_destination_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
