# Generated by Django 3.0.7 on 2020-06-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0003_auto_20200605_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
